//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.RutKiem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListRutKiem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string StampCode { get; set; }
        public string Model { get; set; }
        public string MaterialCode { get; set; }
        public string CheckSum { get; set; }
        public string Color { get; set; }
        public Nullable<int> NumProgramErrors { get; set; }
        public Nullable<int> NumExternalErrors { get; set; }
        public string MachineName { get; set; }
        public string Note { get; set; }
        public string MO { get; set; }
        public Nullable<int> TotalNum { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> LineLeaderId { get; set; }
        public Nullable<int> NumWithDrawals { get; set; }
    
        public virtual WdUser CreatedUser { get; set; }
        public virtual WdUser LineLeaderUser { get; set; }
    }
}
