//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.RutKiem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WithDrawalEntities : DbContext
    {
        public WithDrawalEntities()
            : base("name=WithDrawalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WdUser> WdUsers { get; set; }
        public virtual DbSet<WithDrawalData> WithDrawalDatas { get; set; }
        public virtual DbSet<CheckListRutKiem> CheckListRutKiems { get; set; }
    }
}
