//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.ICColor.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ICColorManager : DbContext
    {
        public ICColorManager()
            : base("name=ICColorManager")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ICColorStatus> ICColorStatus { get; set; }
        public virtual DbSet<ICColor> ICColors { get; set; }
        public virtual DbSet<User_ICColor> User_ICColor { get; set; }
    }
}
