//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.ICColor.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusICColor
    {
        public int Id { get; set; }
        public Nullable<int> IdUser1 { get; set; }
        public Nullable<int> IdUser2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public string Note { get; set; }
        public Nullable<int> IdUserCreated { get; set; }
        public Nullable<int> IdICColor { get; set; }
    
        public virtual User_ICColor UserCreated { get; set; }
        public virtual User_ICColor UserSign1 { get; set; }
        public virtual User_ICColor UserSign2 { get; set; }
    }
}
