//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.Lable.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LableDataFlow_Status
    {
        public int Id { get; set; }
        public Nullable<int> IdUserCreate { get; set; }
        public Nullable<int> IdLineLeader { get; set; }
        public Nullable<int> IdIQPC { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    }
}
