//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.LabelSample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelSample
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ValidDate { get; set; }
        public string MO { get; set; }
        public Nullable<int> IdFoxconnLabel { get; set; }
        public Nullable<int> IdSNLabel { get; set; }
        public Nullable<int> IdMacIDLabel { get; set; }
        public Nullable<int> IdCurrentLabel { get; set; }
        public Nullable<bool> IsHasKey { get; set; }
        public Nullable<int> IdLabelSampleStatus { get; set; }
        public string Note { get; set; }
    
        public virtual FoxconnLabel FoxconnLabel { get; set; }
        public virtual LabelSampleStatu LabelSampleStatu { get; set; }
        public virtual MacIDLabel MacIDLabel { get; set; }
        public virtual SNLabel SNLabel { get; set; }
        public virtual CurrentLabel CurrentLabel { get; set; }
    }
}
