//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.LabelSample.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelSampleStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabelSampleStatus()
        {
            this.LabelSamples = new HashSet<LabelSample>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdUserCreated { get; set; }
        public Nullable<int> IdTE { get; set; }
        public Nullable<int> IdPQE { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelSample> LabelSamples { get; set; }
        public virtual User_LS UserCreated { get; set; }
        public virtual User_LS UserTE { get; set; }
        public virtual User_LS UserPQE { get; set; }
    }
}
