//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckListRutKiem
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string StampCode { get; set; }
        public string Model { get; set; }
        public string MaterialCode { get; set; }
        public string CheckSum { get; set; }
        public string Color { get; set; }
        public Nullable<int> NumColor { get; set; }
        public Nullable<int> NumWithdrawals { get; set; }
        public Nullable<int> NumProgramErrors { get; set; }
        public Nullable<int> NumExternalErrors { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<int> HeadLineId { get; set; }
        public string MachineName { get; set; }
        public string Note { get; set; }
    
        public virtual Users CreatedUsers { get; set; }
        public virtual Users HeadUsers { get; set; }
    }
}
