//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.Lable.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LabelSampleEntities : DbContext
    {
        public LabelSampleEntities()
            : base("name=LabelSampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CurrentLabel> CurrentLabels { get; set; }
        public virtual DbSet<FoxconnLabel> FoxconnLabels { get; set; }
        public virtual DbSet<LabelSample> LabelSamples { get; set; }
        public virtual DbSet<LabelSampleStatus> LabelSampleStatus1 { get; set; }
        public virtual DbSet<SNLabel> SNLabels { get; set; }
        public virtual DbSet<User_LS> User_LS { get; set; }
        public virtual DbSet<MacIDLabel> MacIDLabels { get; set; }
    }
}
