//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.Lable.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelSampleStatus
    {
        public int Id { get; set; }
        public Nullable<int> IdUserCreated { get; set; }
        public Nullable<int> IdTE { get; set; }
        public Nullable<int> IdPQE { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    
        public virtual User_LS UserCreated { get; set; }
        public virtual User_LS UserTE { get; set; }
        public virtual User_LS UserPQE { get; set; }
    }
}
