//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.Lable.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNLabel
    {
        public int Id { get; set; }
        public Nullable<bool> IsBarCode { get; set; }
        public string TimeChangeMethod { get; set; }
        public string FixedCode { get; set; }
        public string RangeCode { get; set; }
        public string LabelCode { get; set; }
        public string CoalPaperSpec { get; set; }
        public string DerivedFrom { get; set; }
        public string LabelImagePath { get; set; }
    }
}
