//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.SMT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnsualMatReqSign_mt
    {
        public int Id { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> SignOrder { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
    
        public virtual User_mt User { get; set; }
    }
}
