//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.SMT.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnusualMatReqEntities : DbContext
    {
        public UnusualMatReqEntities()
            : base("name=UnusualMatReqEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UnsualMatReqSign_mt> UnsualMatReqSign_mt { get; set; }
        public virtual DbSet<UnusualMatReqStatus_mt> UnusualMatReqStatus_mt { get; set; }
        public virtual DbSet<User_mt> User_mt { get; set; }
        public virtual DbSet<Role_mt> Role_mt { get; set; }
        public virtual DbSet<UnusualMatReq_mt> UnusualMatReq_mt { get; set; }
    }
}
