//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPDCheckList.Web.Areas.SMT.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnusualMatReqStatus_mt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnusualMatReqStatus_mt()
        {
            this.UnsualMatReqSigns = new HashSet<UnsualMatReqSign_mt>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdUserCreated { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnsualMatReqSign_mt> UnsualMatReqSigns { get; set; }
        public virtual User_mt UserCreated { get; set; }
    }
}
